# Generated by Django 3.0.6 on 2021-02-27 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=250)),
                ('website', models.URLField(max_length=250)),
                ('image_link', models.URLField(max_length=250)),
                ('gender', models.CharField(max_length=250)),
                ('skills', models.CharField(max_length=250)),
            ],
        ),
    ]
